; PlatformIO Project Configuration
; 暖夕守护 - ESP32-C3 模拟健康采集终端
;
; 开发板: ESP32-C3 (RISC-V)
; 框架:   Arduino
; BLE:    使用 ESP32 内置 BLE 库

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
; 使用 NimBLE 替代默认 Bluedroid，节省 ~60KB Flash
lib_deps =
    h2zero/NimBLE-Arduino@^1.4.1
build_flags =
    -D CONFIG_BT_NIMBLE_ROLE_PERIPHERAL=1
    -D CONFIG_BT_NIMBLE_ROLE_CENTRAL=0
    -D CONFIG_BT_NIMBLE_ROLE_OBSERVER=0
    -D CONFIG_BT_NIMBLE_ROLE_BROADCASTER=1
